var COUNTRY_DATA = {
  'BFA':{name:'Burkina Faso',lieux:["Pics de Sindou", "Cascades de Banfora", "Parc W"]},
  'CPV':{name:'Cap-Vert',lieux:["Île de Sal", "Volcan Fogo", "Mindelo"]},
  'CIV':{name:'Côte d\'Ivoire',lieux:["Basilique de Yamoussoukro", "Grand-Bassam", "Parc du Banco"]},
  'GMB':{name:'Gambie',lieux:["Île Kunta Kinteh", "Plages de Kololi", "Réserve d'Abuko"]},
  'GHA':{name:'Ghana',lieux:["Château de Cape Coast", "Chutes de Wli", "Parc de Mole"]},
  'GIN':{name:'Guinée',lieux:["Mont Nimba", "Îles de Los", "Fouta Djallon"]},
  'GNB':{name:'Guinée-Bissau',lieux:["Archipel des Bijagós", "Forêt de Cantanhez", "Fortaleza d'Amura"]},
  'LBR':{name:'Liberia',lieux:["Plage de Robertsport", "Parc de Sapo", "Providence Island"]},
  'MLI':{name:'Mali',lieux:["Mosquée de Djenné", "Falaises de Bandiagara", "Tombouctou"]},
  'NER':{name:'Niger',lieux:["Désert du Ténéré", "Mosquée d'Agadez", "Parc W"]},
  'NGA':{name:'Nigeria',lieux:["Rocher de Zuma", "Parc de Yankari", "Tarkwa Bay"]},
  'SEN':{name:'Sénégal',lieux:["Île de Gorée", "Lac Rose", "Parc du Djoudj"]},
  'SLE':{name:'Sierra Leone',lieux:["Plages de Freetown", "Île Bunce", "Forêt de Gola"]},
  'TGO':{name:'Togo',lieux:["Cascades de Kpimé", "Grand Marché de Lomé", "Parc de Fazao"]},
  'AGO':{name:'Angola',lieux:["Chutes de Kalandula", "Fenda da Tundavala", "Forteresse de São Miguel"]},
  'BDI':{name:'Burundi',lieux:["Lac Tanganyika", "Source du Nil", "Parc de Rusizi"]},
  'CAF':{name:'Centrafrique',lieux:["Chutes de Boali", "Parc de Dzanga-Sangha", "Forêt du Congo"]},
  'TCD':{name:'Tchad',lieux:["Lac Tchad", "Montagnes du Tibesti", "Parc de Zakouma"]},
  'COM':{name:'Comores',lieux:["Volcan Karthala", "Plage d'Itsandra", "Médina de Mutsamudu"]},
  'COG':{name:'Congo',lieux:["Gorges du Djoué", "Parc d'Odzala", "Basilique Sainte-Anne"]},
  'COD':{name:'RD Congo',lieux:["Volcans du Virunga", "Chutes de Boyoma", "Parc de Kahuzi-Biega"]},
  'DJI':{name:'Djibouti',lieux:["Lac Assal", "Lac Abbé", "Forêt du Day"]},
  'GNQ':{name:'Guinée équatoriale',lieux:["Pic Basilé", "Plages d'Ureca", "Île de Bioko"]},
  'ETH':{name:'Éthiopie',lieux:["Églises de Lalibela", "Montagnes du Simien", "Dépression du Danakil"]},
  'GAB':{name:'Gabon',lieux:["Parc de Lopé", "Pointe Denis", "Cap Estérias"]},
  'KEN':{name:'Kenya',lieux:["Réserve du Masai Mara", "Mont Kenya", "Plages de Diani"]},
  'LSO':{name:'Lesotho',lieux:["Chutes de Maletsunyane", "Parc de Ts'ehlanyane", "Katse Dam"]},
  'MDG':{name:'Madagascar',lieux:["Allée des Baobabs", "Tsingy de Bemaraha", "Île Sainte-Marie"]},
  'MWI':{name:'Malawi',lieux:["Lac Malawi", "Mont Mulanje", "Parc de Liwonde"]},
  'MRT':{name:'Mauritanie',lieux:["Chinguetti", "Banc d'Arguin", "Structure de Richat"]},
  'MUS':{name:'Île Maurice',lieux:["Le Morne Brabant", "Terre des 7 Couleurs", "Île aux Cerfs"]},
  'MOZ':{name:'Mozambique',lieux:["Archipel de Bazaruto", "Île de Mozambique", "Parc de Gorongosa"]},
  'NAM':{name:'Namibie',lieux:["Dunes de Sossusvlei", "Parc Etosha", "Skeleton Coast"]},
  'RWA':{name:'Rwanda',lieux:["Gorilles du Virunga", "Lac Kivu", "Mémorial de Kigali"]},
  'STP':{name:'São Tomé',lieux:["Pico Cão Grande", "Plage Jalé", "Roça Sundy"]},
  'SYC':{name:'Seychelles',lieux:["Anse Source d'Argent", "Vallée de Mai", "La Digue"]},
  'SOM':{name:'Somalie',lieux:["Grottes de Laas Geel", "Plage de Liido", "Ruines de Barawa"]},
  'ZAF':{name:'Afrique du Sud',lieux:["Table Mountain", "Parc Kruger", "Route des Jardins"]},
  'TZA':{name:'Tanzanie',lieux:["Mont Kilimandjaro", "Serengeti", "Zanzibar"]},
  'UGA':{name:'Ouganda',lieux:["Forêt de Bwindi", "Chutes de Murchison", "Monts Rwenzori"]},
  'ZMB':{name:'Zambie',lieux:["Chutes Victoria", "South Luangwa", "Lac Kariba"]},
  'ZWE':{name:'Zimbabwe',lieux:["Ruines du Grand Zimbabwe", "Parc de Hwange", "Matobo Hills"]},
  'BGD':{name:'Bangladesh',lieux:["Sundarbans", "Cox's Bazar", "Mosquée des 60 Dômes"]},
  'KHM':{name:'Cambodge',lieux:["Angkor Wat", "Palais Royal Phnom Penh", "Sihanoukville"]},
  'HKG':{name:'Hong Kong',lieux:["Victoria Peak", "Grand Bouddha Tian Tan", "Port de Victoria"]},
  'IRN':{name:'Iran',lieux:["Persépolis", "Place Naghsh-e Jahan", "Mosquée Nasir ol-Molk"]},
  'LAO':{name:'Laos',lieux:["Luang Prabang", "Chutes de Kuang Si", "Vang Vieng"]},
  'MAC':{name:'Macao',lieux:["Ruines de Saint-Paul", "Tour de Macao", "Senado Square"]},
  'MYS':{name:'Malaisie',lieux:["Tours Petronas", "Grottes de Batu", "Île de Langkawi"]},
  'MDV':{name:'Maldives',lieux:["Atolls de Malé", "Bungalows sur l'eau", "Plongée Ari Atoll"]},
  'NPL':{name:'Népal',lieux:["Everest Base Camp", "Temples de Katmandou", "Pokhara"]},
  'PAK':{name:'Pakistan',lieux:["Vallée de Hunza", "Mosquée Badshahi", "K2 Base Camp"]},
  'PHL':{name:'Philippines',lieux:["El Nido Palawan", "Chocolate Hills Bohol", "Rizières de Banaue"]},
  'SGP':{name:'Singapour',lieux:["Gardens by the Bay", "Marina Bay Sands", "Sentosa Island"]},
  'LKA':{name:'Sri Lanka',lieux:["Rocher de Sigiriya", "Temple de la Dent", "Plages de Mirissa"]},
  'TJK':{name:'Tadjikistan',lieux:["Route du Pamir", "Lac Iskanderkul", "Forteresse de Hisor"]},
  'TLS':{name:'Timor oriental',lieux:["Cristo Rei de Dili", "Île d'Ataúro", "Plage de Jaco"]},
  'COK':{name:'Îles Cook',lieux:["Lagon d'Aitutaki", "Plage de Muri", "Île de Rarotonga"]},
  'FSM':{name:'Micronésie',lieux:["Ruines de Nan Madol", "Lagon de Chuuk", "Île de Yap"]},
  'KIR':{name:'Kiribati',lieux:["Atoll de Tarawa", "Île Christmas", "Lagon de Kiritimati"]},
  'NIU':{name:'Niue',lieux:["Matapa Chasm", "Piscines naturelles", "Forêt de Huvalu"]},
  'PLW':{name:'Palaos',lieux:["Lac aux Méduses", "Rock Islands", "Blue Corner"]},
  'WSM':{name:'Samoa',lieux:["To Sua Ocean Trench", "Plage de Lalomanu", "Cascades de Papapapaitai"]},
  'TUV':{name:'Tuvalu',lieux:["Atoll de Funafuti", "Lagon de Nanumea", "Conservation Area"]},
  'BHS':{name:'Bahamas',lieux:["Plage de Pink Sands", "Exuma Cays", "Nassau Fort Charlotte"]},
  'BRB':{name:'Barbade',lieux:["Plage de Crane", "Harrison's Cave", "Bridgetown"]},
  'BLZ':{name:'Belize',lieux:["Grand Trou Bleu", "Ruines de Xunantunich", "Caye Caulker"]},
  'BOL':{name:'Bolivie',lieux:["Salar d'Uyuni", "Lac Titicaca", "Forêt des Yungas"]},
  'DMA':{name:'Dominique',lieux:["Boiling Lake", "Chutes de Trafalgar", "Champagne Reef"]},
  'ECU':{name:'Équateur',lieux:["Îles Galápagos", "Quito colonial", "Volcan Cotopaxi"]},
  'HTI':{name:'Haïti',lieux:["Citadelle Laferrière", "Bassin Bleu", "Labadee"]},
  'NIC':{name:'Nicaragua',lieux:["Île d'Ometepe", "Granada coloniale", "Corn Islands"]},
  'VCT':{name:'Saint-Vincent',lieux:["Tobago Cays", "La Soufrière", "Plages noires"]},
  'SUR':{name:'Suriname',lieux:["Paramaribo historique", "Réserve de Brownsberg", "Forêt amazonienne"]},
  'TUN':{name:'Tunisie',lieux:["Sidi Bou Saïd", "Ruines de Carthage", "Désert de Douz"]},
  'OMN':{name:'Oman',lieux:["Grande Mosquée de Mascate", "Wadi Shab", "Désert de Wahiba"]},
  'PSE':{name:'Palestine',lieux:["Vieille ville de Bethléem", "Jéricho", "Mer Morte"]},
};